import json

from ai_analyzer import client


def explain_forecast(
    historical_data,
    forecast_data,
    analysis_data
):

    prompt = f"""
You are GreenPulse AI, an energy forecasting analyst.

Analyze the historical energy consumption and the
forecast generated by a machine-learning model.

HISTORICAL DATA:
{json.dumps(historical_data, indent=2)}

FORECAST:
{json.dumps(forecast_data, indent=2)}

ADDITIONAL ENERGY ANALYSIS:
{json.dumps(analysis_data, indent=2)}

Provide a concise explanation of the forecast.

Identify:

1. Whether consumption is increasing, decreasing,
   or relatively stable.
2. The expected change from the first forecast value
   to the last forecast value.
3. Which appliance or historical pattern should be
   monitored based on the available data.
4. One practical action the user can take.

Rules:

- The forecast values come from a machine-learning
  model. Do not change or recalculate them.
- Base your explanation only on the supplied data.
- Do not claim that the forecast is certain.
- Do not invent causes that aren't supported by the data.
- Clearly describe the forecast as an estimate.
- Keep the answer simple and concise.

Return ONLY valid JSON:

{{
    "trend": "increasing/decreasing/stable",

    "summary": "Short explanation of the forecast",

    "change": "Describe the change between the first
    and last forecast values",

    "monitor": "What the user should monitor",

    "action": "One practical recommended action"
}}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    text = response.text.strip()

    if text.startswith("```"):
        text = text.replace("```json", "")
        text = text.replace("```", "")
        text = text.strip()

    return json.loads(text)